---

- name: key
  apt_key: >
    url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state=present
  when: ansible_os_family == "Debian"
  sudo: yes

- name: repositories
  apt_repository: >
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - deb http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg main
  when: ansible_os_family == "Debian"
  sudo: yes

- name: packages
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - postgresql-9.3
    - postgresql-client-9.3
    - postgresql-server-dev-9.3
    - libpq-dev
    - python-dev
    - postgresql-contrib-9.3
    - php5-pgsql
  notify:
    - php restart
  when: ansible_os_family == "Debian"
  sudo: yes

- name: psycopg2
  pip: >
    name=psycopg2
  sudo: yes

- name: postgresql config 1
  lineinfile: >
    dest=/etc/postgresql/9.3/main/pg_hba.conf
    line="local all all trust"
    state=present
    regexp="^local all all trust$"
    insertbefore="^# DO NOT DISABLE!"
  sudo: yes

- name: postgresql config 2
  lineinfile: >
    dest=/etc/postgresql/9.3/main/pg_hba.conf
    line="host all all 172.16.1.1/32 md5"
    state=present
    regexp="^host all all 172.16.1.1/32 md5$"
    insertbefore="^# DO NOT DISABLE!"
  sudo: yes

- name: postgresql config 3
  lineinfile: >
    dest=/etc/postgresql/9.3/main/postgresql.conf
    line="listen_addresses = '*'                  # what IP address(es) to listen on;"
    state=present
    regexp="^#?listen_addresses = "
  sudo: yes

- name: service
  service: >
    name=postgresql
    state=started
    enabled=yes
  sudo: yes

- name: user
  postgresql_user: >
    name=root
    password="root"
    role_attr_flags=CREATEDB,CREATEROLE,SUPERUSER
    state=present
  sudo: yes
