Birgit\Bundle\TaskDoctrineBundle\Entity\Task\Queue\TaskQueue:
    type:  entity
    table: birgit_task_queue
    repositoryClass: Birgit\Bundle\TaskDoctrineBundle\Entity\Task\Queue\TaskQueueRepository
    id:
        id:
            column:    id
            type:      guid
            generator: { strategy: UUID }
    fields:
        # Status
        status:
            column:    status
            type:      integer
        # Attempts
        attempts:
            column:    attempts
            type:      integer
        # Handler definition
        handlerType:
            column:    handler_type
            type:      string
            length:    255
        handlerParameters:
            column:    handler_parameters
            type:      parameters
    oneToMany:
        tasks:
            targetEntity: Birgit\Bundle\TaskDoctrineBundle\Entity\Task\Task
            mappedBy:     queue
            cascade:      ['persist']
        children:
            targetEntity: Birgit\Bundle\TaskDoctrineBundle\Entity\Task\Queue\TaskQueue
            mappedBy:     parent
    manyToOne:
        parent:
            targetEntity: Birgit\Bundle\TaskDoctrineBundle\Entity\Task\Queue\TaskQueue
            inversedBy:   children
            joinColumn:
                name:      parent_id
                nullable:  true
