birgit_host:
    resource: "@BirgitHostBundle/Controller/"
    type:     annotation
    prefix:   /

birgit_repository:
    resource: "@BirgitRepositoryBundle/Controller/"
    type:     annotation
    prefix:   /

birgit_project:
    resource: "@BirgitProjectBundle/Controller/"
    type:     annotation
    prefix:   /

