birgit_api:
    resource: "@BirgitApiBundle/Controller/"
    type:     annotation
    prefix:   /api

birgit_front:
    resource: "@BirgitFrontBundle/Controller/"
    type:     annotation
    prefix:   /
