birgit_repository:
    resource: "@BirgitRepositoryBundle/Controller/"
    type:     annotation
    prefix:   /

birgit_project:
    resource: "@BirgitProjectBundle/Controller/"
    type:     annotation
    prefix:   /

