---

- name: packages
  apt: >
      pkg={{ item }}
      state=present
  with_items:
      - xvfb
  sudo: yes

- name: service template
  template: >
      src=service.j2
      dest=/etc/init.d/xvfbd
  sudo: yes

- name: service file
  file: >
      path=/etc/init.d/xvfbd
      state=file
      group=root
      owner=root
      mode=0755
  sudo: yes

- name: service install
  shell: >
      /usr/sbin/update-rc.d xvfbd defaults
      creates=/etc/rc0.d/K01xvfbd
  sudo: yes

- name: service
  service: >
      name=xvfbd
      state=started
      enabled=true
  sudo: yes

- name: profile template
  template: >
      src=profile.sh.j2
      dest=/etc/profile.d/xvfb.sh
  sudo: yes

- name: profile file
  file: >
      path=/etc/profile.d/xvfb.sh
      state=file
      owner=root
      group=root
      mode=0644
  sudo: yes
