Birgit\Component\Task\Bundle\DoctrineBundle\Entity\Task\Task:
    type:  entity
    table: birgit_task
    repositoryClass: Birgit\Component\Task\Bundle\DoctrineBundle\Entity\Task\TaskRepository
    id:
        id:
            column:    id
            type:      guid
            generator: { strategy: UUID }
    fields:
        # Status
        status:
            column:    status
            type:      integer
        # Attempts
        attempts:
            column:    attempts
            type:      integer
        # Type definition
        typeAlias:
            column:    type_alias
            type:      string
            length:    255
        typeParameters:
            column:    type_parameters
            type:      json_array
    manyToOne:
        queue:
            targetEntity: Birgit\Component\Task\Bundle\DoctrineBundle\Entity\Task\Queue\TaskQueue
            inversedBy:   tasks
            joinColumn:
                name:      queue_id
                nullable:  false
