Birgit\Bundle\DoctrineBundle\Entity\Build\Build:
    type:            entity
    table:           birgit_build
    repositoryClass: Birgit\Bundle\DoctrineBundle\Entity\Build\BuildRepository
    id:
        id:
            column:    id
            type:      guid
            generator: { strategy: UUID }
    manyToOne:
        host:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Host\Host
            inversedBy:   builds
            joinColumn:
                name:      host_id
                nullable:  false
        projectReferenceRevision:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Project\Reference\Revision\ProjectReferenceRevision
            inversedBy:   builds
            joinColumn:
                name:      project_reference_revision_id
                nullable:  false
