Birgit\Bundle\DoctrineBundle\Entity\Project\Project:
    type:            entity
    table:           birgit_project
    repositoryClass: Birgit\Bundle\DoctrineBundle\Entity\Project\ProjectRepository
    uniqueConstraints:
        name:
            columns: ['name']
    id:
        id:
            column:    id
            type:      integer
            generator: { strategy: AUTO }
    fields:
        name:
            column:    name
            type:      string
            length:    255
        status:
            column:    status
            type:      integer
        active:
            column:    active
            type:      boolean
        # Handler definition
        handlerType:
            column:    handler_type
            type:      string
            length:    255
        handlerParameters:
            column:    handler_parameters
            type:      parameters
    oneToMany:
        references:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Project\Reference\ProjectReference
            mappedBy:     project
            cascade:      ['persist']
        environments:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Project\Environment\ProjectEnvironment
            mappedBy:     project
            cascade:      ['persist']
