Birgit\Bundle\DoctrineBundle\Entity\Project\Environment\ProjectEnvironment:
    type:            entity
    table:           birgit_project_environment
    repositoryClass: Birgit\Bundle\DoctrineBundle\Entity\Project\Environment\ProjectEnvironmentRepository
    uniqueConstraints:
        project_id_name:
            columns: ['project_id', 'name']
    id:
        id:
            type:      integer
            generator: { strategy: AUTO }
    fields:
        name:
            type:     string
            length:   255
        type:
            type:     string
            length:   255
        parameters:
            type:     parameters
        referencePattern:
            type:     string
            length:   255
        active:
            type:     boolean
    manyToOne:
        project:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Project\Project
            inversedBy:   environments
            joinColumn:
                nullable: false
    oneToMany:
        hosts:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Host\Host
            mappedBy:     projectEnvironment
            cascade:      ['persist']
