Birgit\Bundle\DoctrineBundle\Entity\Project\Environment\ProjectEnvironment:
    type:            entity
    table:           birgit_project_environment
    repositoryClass: Birgit\Bundle\DoctrineBundle\Entity\Project\Environment\ProjectEnvironmentRepository
    uniqueConstraints:
        project_id_name:
            columns: ['project_id', 'name']
    id:
        id:
            column:    id
            type:      integer
            generator: { strategy: AUTO }
    fields:
        name:
            column:    name
            type:      string
            length:    255
        referencePattern:
            column:    reference_pattern
            type:      string
            length:    255
        active:
            column:    active
            type:      boolean
        # Handler definition
        handlerType:
            column:    handler_type
            type:      string
            length:    255
        handlerParameters:
            column:    handler_parameters
            type:      parameters
    manyToOne:
        project:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Project\Project
            inversedBy:   environments
            joinColumn:
                name:      project_id
                nullable:  false
    oneToMany:
        hosts:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Host\Host
            mappedBy:     projectEnvironment
            cascade:      ['persist']
