Birgit\Bundle\DoctrineBundle\Entity\Project\Environment\ProjectEnvironment:
    type:            entity
    table:           birgit_project_environment
    repositoryClass: Birgit\Bundle\DoctrineBundle\Entity\Project\Environment\ProjectEnvironmentRepository
    uniqueConstraints:
        project_id_name:
            columns: ['project_id', 'name']
    id:
        id:
            name:      id
            type:      integer
            generator: { strategy: AUTO }
    fields:
        name:
            name:      name
            type:      string
            length:    255
        type:
            name:      type
            type:      string
            length:    255
        parameters:
            name:      parameters
            type:      parameters
        referencePattern:
            name:      reference_pattern
            type:      string
            length:    255
        active:
            name:      active
            type:      boolean
    manyToOne:
        project:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Project\Project
            inversedBy:   environments
            joinColumn:
                name:      project_id
                nullable:  false
    oneToMany:
        hosts:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Host\Host
            mappedBy:     projectEnvironment
            cascade:      ['persist']
