Birgit\Bundle\DoctrineBundle\Entity\Project\Reference\ProjectReference:
    type:            entity
    table:           birgit_project_reference
    repositoryClass: Birgit\Bundle\DoctrineBundle\Entity\Project\Reference\ProjectReferenceRepository
    uniqueConstraints:
        project_id_name:
            columns: ['project_id', 'name']
    id:
        id:
            name:      id
            type:      integer
            generator: { strategy: AUTO }
    fields:
        name:
            name:      name
            type:      string
            length:    255
    manyToOne:
        project:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Project\Project
            inversedBy:   references
            joinColumn:
                name:      project_id
                nullable:  false
    oneToMany:
        revisions:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Project\Reference\Revision\ProjectReferenceRevision
            mappedBy:     reference
            cascade:      ['persist']
        hosts:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Host\Host
            mappedBy:     projectReference
            cascade:      ['persist']
