Birgit\Bundle\DoctrineBundle\Entity\Project\Project:
    type:            entity
    table:           birgit_project
    repositoryClass: Birgit\Bundle\DoctrineBundle\Entity\Project\ProjectRepository
    uniqueConstraints:
        name:
            columns: ['name']
    id:
        id:
            name:      id
            type:      integer
            generator: { strategy: AUTO }
    fields:
        name:
            name:      name
            type:      string
            length:    255
        status:
            name:      status
            type:      integer
        active:
            name:      active
            type:      boolean
        # Handler definition
        handlerType:
            name:      handler_type
            type:      string
            length:    255
        handlerParameters:
            name:      handler_parameters
            type:      parameters
    oneToMany:
        references:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Project\Reference\ProjectReference
            mappedBy:     project
            cascade:      ['persist']
        environments:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Project\Environment\ProjectEnvironment
            mappedBy:     project
            cascade:      ['persist']
