Birgit\Bundle\DoctrineBundle\Entity\Task\Task:
    type:  entity
    table: birgit_task
    repositoryClass: Birgit\Bundle\DoctrineBundle\Entity\Task\TaskRepository
    id:
        id:
            name:      id
            type:      integer
            generator: { strategy: AUTO }
    fields:
        # Handler definition
        handlerType:
            name:      handler_type
            type:      string
            length:    255
        handlerParameters:
            name:      handler_parameters
            type:      parameters
    manyToOne:
        queue:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Task\Queue\TaskQueue
            inversedBy:   tasks
            joinColumn:
                name:      queue_id
                nullable:  false
