Birgit\Bundle\DoctrineBundle\Entity\Task\Task:
    type:  entity
    table: birgit_task
    repositoryClass: Birgit\Bundle\DoctrineBundle\Entity\Task\TaskRepository
    id:
        id:
            column:    id
            type:      integer
            generator: { strategy: AUTO }
    fields:
        # Status
        status:
            column:    status
            type:      integer
        # Attempts
        attempts:
            column:    attempts
            type:      integer
        # Handler definition
        handlerType:
            column:    handler_type
            type:      string
            length:    255
        handlerParameters:
            column:    handler_parameters
            type:      parameters
    manyToOne:
        queue:
            targetEntity: Birgit\Bundle\DoctrineBundle\Entity\Task\Queue\TaskQueue
            inversedBy:   tasks
            joinColumn:
                name:      queue_id
                nullable:  false
