---

- name: packages
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - nodejs
    - nodejs-legacy
  sudo: yes

- name: npm install path
  file: >
      path=/opt/npm
      state=directory
  sudo: yes

- name: npm install file
  get_url: >
      url=https://www.npmjs.org/install.sh
      dest=/opt/npm/install.sh
  sudo: yes

- name: npm install
  shell: >
      sh /opt/npm/install.sh
      creates=/usr/bin/npm
  sudo: yes
