Birgit\Bundle\CoreBundle\Entity\Project\Reference\ProjectReference:
    type:            entity
    table:           birgit_project_reference
    repositoryClass: Birgit\Bundle\CoreBundle\Entity\Project\Reference\ProjectReferenceRepository
    uniqueConstraints:
        project_id_name:
            columns: ['project_id', 'name']
    id:
        id:
            type:      integer
            generator: { strategy: AUTO }
    fields:
        name:
            type:     string
            length:   255
    manyToOne:
        project:
            targetEntity: Birgit\Bundle\CoreBundle\Entity\Project\Project
            inversedBy:   references
            joinColumn:
                nullable: false
    oneToMany:
        revisions:
            targetEntity: Birgit\Bundle\CoreBundle\Entity\Project\Reference\Revision\ProjectReferenceRevision
            mappedBy:     reference
            cascade:      ['persist']
        hosts:
            targetEntity: Birgit\Bundle\CoreBundle\Entity\Host\Host
            mappedBy:     projectReference
            cascade:      ['persist']
