Birgit\Bundle\CoreBundle\Entity\Project\Reference\Revision\ProjectReferenceRevision:
    type:            entity
    table:           birgit_project_reference_revision
    repositoryClass: Birgit\Bundle\CoreBundle\Entity\Project\Reference\Revision\ProjectReferenceRevisionRepository
    uniqueConstraints:
        reference_id_name:
            columns: ['reference_id', 'name']
    id:
        id:
            type:      integer
            generator: { strategy: AUTO }
    fields:
        name:
            type:     string
            length:   255
    manyToOne:
        reference:
            targetEntity: Birgit\Bundle\CoreBundle\Entity\Project\Reference\ProjectReference
            inversedBy:   revisions
            joinColumn:
                nullable: false
    oneToMany:
        builds:
            targetEntity: Birgit\Bundle\CoreBundle\Entity\Build\Build
            mappedBy:     projectReferenceRevision
            cascade:      ['persist']
