Birgit\Bundle\CoreBundle\Entity\Project\Environment\ProjectEnvironment:
    type:            entity
    table:           birgit_project_environment
    repositoryClass: Birgit\Bundle\CoreBundle\Entity\Project\Environment\ProjectEnvironmentRepository
    uniqueConstraints:
        project_id_name:
            columns: ['project_id', 'name']
    id:
        id:
            type:      integer
            generator: { strategy: AUTO }
    fields:
        name:
            type:   string
            length: 255
        repositoryReferencePattern:
            type:   string
            length: 255
        active:
            type:   boolean
    manyToOne:
        project:
            targetEntity: Birgit\Bundle\CoreBundle\Entity\Project\Project
            inversedBy:   environments
            joinColumn:
                nullable: false
        hostProvider:
            targetEntity: Birgit\Bundle\CoreBundle\Entity\Host\Provider\HostProvider
            inversedBy:   projectEnvironments
            joinColumn:
                nullable: false
    oneToMany:
        hosts:
            targetEntity: Birgit\Bundle\CoreBundle\Entity\Host\Host
            mappedBy:     projectEnvironment
            cascade:      ['persist']
