Birgit\Bundle\CoreBundle\Entity\Repository\Reference\RepositoryReference:
    type:            entity
    table:           birgit_repository_reference
    repositoryClass: Birgit\Bundle\CoreBundle\Entity\Repository\Reference\RepositoryReferenceRepository
    uniqueConstraints:
        repository_id_name:
            columns: ['repository_id', 'name']
    id:
        id:
            type:      integer
            generator: { strategy: AUTO }
    fields:
        name:
            type:   string
            length: 255
    manyToOne:
        repository:
            targetEntity: Birgit\Bundle\CoreBundle\Entity\Repository\Repository
            inversedBy:   references
            joinColumn:
                nullable: false
    oneToMany:
        revisions:
            targetEntity: Birgit\Bundle\CoreBundle\Entity\Repository\Reference\Revision\RepositoryReferenceRevision
            mappedBy:     reference
            cascade:      ['persist']
        hosts:
            targetEntity: Birgit\Bundle\CoreBundle\Entity\Host\Host
            mappedBy:     repositoryReference
            cascade:      ['persist']
