Birgit\Bundle\CoreBundle\Entity\Task\Queue\TaskQueue:
    type:  entity
    table: birgit_task_queue
    repositoryClass: Birgit\Bundle\CoreBundle\Entity\Task\Queue\TaskQueueRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        type:
            type:     string
            length:   255
        parameters:
            type:     parameters
    oneToMany:
        tasks:
            targetEntity: Birgit\Bundle\CoreBundle\Entity\Task\Task
            mappedBy:     queue
            cascade:      ['persist']
