Birgit\Component\Event\Bundle\DoctrineBundle\Entity\Event\Event:
    type:  entity
    table: birgit_event
    repositoryClass: Birgit\Component\Event\Bundle\DoctrineBundle\Entity\Event\EventRepository
    id:
        id:
            column:    id
            type:      integer
            generator: { strategy: AUTO }
    fields:
        name:
            column:    name
            type:      string
            length:    255
        parameters:
            column:    parameters
            type:      json_array
