---

- name: key
  apt_key: >
      url=http://www.dotdeb.org/dotdeb.gpg
      state=present
  sudo: yes

- name: repositories
  apt_repository: >
      repo="{{ item }}"
      state=present
      update_cache=yes
  with_items:
      - deb http://packages.dotdeb.org wheezy all
      - deb-src http://packages.dotdeb.org wheezy all
      - deb http://packages.dotdeb.org wheezy-php55 all
      - deb-src http://packages.dotdeb.org wheezy-php55 all
  sudo: yes
