---

- name: repositories
  apt_repository: >
      repo="{{ item }}"
      state=present
      update_cache=yes
  with_items:
      - deb ftp://ftp.debian.org/debian stable contrib non-free
  sudo: yes
