---

- name: path
  file: >
      path=/opt/selenium
      state=directory
  sudo: yes

- name: install
  get_url: >
      url=http://selenium.googlecode.com/files/selenium-server-standalone-2.37.0.jar
      dest=/opt/selenium/selenium-server-standalone.jar
  sudo: yes

- name: service template
  template: >
      src=seleniumd.j2
      dest=/etc/init.d/seleniumd
  sudo: yes

- name: service install
  shell: >
      /usr/sbin/update-rc.d seleniumd defaults
      creates=/etc/rc0.d/K01seleniumd
  sudo: yes

- name: service file
  file: >
      path=/etc/init.d/seleniumd
      state=file
      group=root
      owner=root
      mode=0755
  sudo: yes

- name: service
  service: >
      name=seleniumd
      state=started
      enabled=true
  sudo: yes
